# Generated by Django 5.1.4 on 2024-12-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Socializer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.CharField(max_length=500),
        ),
    ]
