# Generated by Django 5.1.4 on 2024-12-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Socializer", "0002_alter_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="latitude",
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="longitude",
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
