# Generated by Django 5.1.4 on 2024-12-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socializer', '0003_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
